//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerox.Wnc.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xerox.Wnc.Resources.Resources.AppsResource", typeof(AppsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
          
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        public static string AGREE {
            get {
                return ResourceManager.GetString("AGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disagree.
        /// </summary>
        public static string DISAGREE {
            get {
                return ResourceManager.GetString("DISAGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11&quot; x 17&quot; (Landscape).
        /// </summary>
        public static string SDE_11_X_172 {
            get {
                return ResourceManager.GetString("SDE_11_X_172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11 x 17&quot;.
        /// </summary>
        public static string SDE_11_X_173 {
            get {
                return ResourceManager.GetString("SDE_11_X_173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-Sided.
        /// </summary>
        public static string SDE_1SIDED {
            get {
                return ResourceManager.GetString("SDE_1SIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Sided.
        /// </summary>
        public static string SDE_2SIDED {
            get {
                return ResourceManager.GetString("SDE_2SIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Sided Printing.
        /// </summary>
        public static string SDE_2SIDED_PRINTING2 {
            get {
                return ResourceManager.GetString("SDE_2SIDED_PRINTING2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Sided, Rotate Side 2.
        /// </summary>
        public static string SDE_2SIDED_ROTATE_SIDE {
            get {
                return ResourceManager.GetString("SDE_2SIDED_ROTATE_SIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Sided Scanning.
        /// </summary>
        public static string SDE_2SIDED_SCANNING {
            get {
                return ResourceManager.GetString("SDE_2SIDED_SCANNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A3 (Landscape).
        /// </summary>
        public static string SDE_A3_LANDSCAPE1 {
            get {
                return ResourceManager.GetString("SDE_A3_LANDSCAPE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A3.
        /// </summary>
        public static string SDE_A31 {
            get {
                return ResourceManager.GetString("SDE_A31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4 (Landscape).
        /// </summary>
        public static string SDE_A4_LANDSCAPE1 {
            get {
                return ResourceManager.GetString("SDE_A4_LANDSCAPE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4 (Portrait).
        /// </summary>
        public static string SDE_A4_PORTRAIT1 {
            get {
                return ResourceManager.GetString("SDE_A4_PORTRAIT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4.
        /// </summary>
        public static string SDE_A41 {
            get {
                return ResourceManager.GetString("SDE_A41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SDE_ABOUT {
            get {
                return ResourceManager.GetString("SDE_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to remove the document from your device..
        /// </summary>
        public static string SDE_ABOUT_REMOVE_DOCUMENT {
            get {
                return ResourceManager.GetString("SDE_ABOUT_REMOVE_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string SDE_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("SDE_ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        public static string SDE_ACCESS_DENIED1 {
            get {
                return ResourceManager.GetString("SDE_ACCESS_DENIED1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string SDE_ACCOUNT {
            get {
                return ResourceManager.GetString("SDE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        public static string SDE_ACCOUNT_DETAILS {
            get {
                return ResourceManager.GetString("SDE_ACCOUNT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Invitation.
        /// </summary>
        public static string SDE_ACCOUNT_INVITATION {
            get {
                return ResourceManager.GetString("SDE_ACCOUNT_INVITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been suspended..
        /// </summary>
        public static string SDE_ACCOUNT_SUSPENDED {
            get {
                return ResourceManager.GetString("SDE_ACCOUNT_SUSPENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action confirmation.
        /// </summary>
        public static string SDE_ACTION_CONFIRMATION {
            get {
                return ResourceManager.GetString("SDE_ACTION_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string SDE_ACTIVE {
            get {
                return ResourceManager.GetString("SDE_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Account.
        /// </summary>
        public static string SDE_ADMINISTRATOR_ACCOUNT {
            get {
                return ResourceManager.GetString("SDE_ADMINISTRATOR_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator account already exists..
        /// </summary>
        public static string SDE_ADMINISTRATOR_ACCOUNT_ALREADY {
            get {
                return ResourceManager.GetString("SDE_ADMINISTRATOR_ACCOUNT_ALREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator account created..
        /// </summary>
        public static string SDE_ADMINISTRATOR_ACCOUNT_CREATED {
            get {
                return ResourceManager.GetString("SDE_ADMINISTRATOR_ACCOUNT_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Account Setup.
        /// </summary>
        public static string SDE_ADMINISTRATOR_ACCOUNT_SETUP {
            get {
                return ResourceManager.GetString("SDE_ADMINISTRATOR_ACCOUNT_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Documents.
        /// </summary>
        public static string SDE_ALL_DOCUMENTS {
            get {
                return ResourceManager.GetString("SDE_ALL_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string SDE_ALL_RIGHTS_RESERVED1 {
            get {
                return ResourceManager.GetString("SDE_ALL_RIGHTS_RESERVED1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All scans will be created as separate attachments..
        /// </summary>
        public static string SDE_ALL_SCANS_WILL {
            get {
                return ResourceManager.GetString("SDE_ALL_SCANS_WILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sub-accounts associated with your account will also be deleted..
        /// </summary>
        public static string SDE_ALL_SUBACCOUNTS_ASSOCIATED {
            get {
                return ResourceManager.GetString("SDE_ALL_SUBACCOUNTS_ASSOCIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App ID.
        /// </summary>
        public static string SDE_APP_ID {
            get {
                return ResourceManager.GetString("SDE_APP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Error.
        /// </summary>
        public static string SDE_APPLICATION_ERROR {
            get {
                return ResourceManager.GetString("SDE_APPLICATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application for storage viewing not found.
        /// </summary>
        public static string SDE_APPLICATION_STORAGE_VIEWING {
            get {
                return ResourceManager.GetString("SDE_APPLICATION_STORAGE_VIEWING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archival (PDF/A).
        /// </summary>
        public static string SDE_ARCHIVAL_PDFA {
            get {
                return ResourceManager.GetString("SDE_ARCHIVAL_PDFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Document.
        /// </summary>
        public static string SDE_AUDIO_DOCUMENT {
            get {
                return ResourceManager.GetString("SDE_AUDIO_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Audio Documents account has been updated..
        /// </summary>
        public static string SDE_AUDIO_DOCUMENTS_ACCOUNT {
            get {
                return ResourceManager.GetString("SDE_AUDIO_DOCUMENTS_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Audio Documents account has been created..
        /// </summary>
        public static string SDE_AUDIO_DOCUMENTS_ACCOUNT1 {
            get {
                return ResourceManager.GetString("SDE_AUDIO_DOCUMENTS_ACCOUNT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Audio Documents job exceeded the maximum number of pages allowed. Please reduce the number of pages to {0} or less.  Note, anything larger than 8.5 x 11&quot; or A4 counts as 2 pages..
        /// </summary>
        public static string SDE_AUDIO_DOCUMENTS_JOB {
            get {
                return ResourceManager.GetString("SDE_AUDIO_DOCUMENTS_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Documents Log In.
        /// </summary>
        public static string SDE_AUDIO_DOCUMENTS_LOG {
            get {
                return ResourceManager.GetString("SDE_AUDIO_DOCUMENTS_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Documents is not able to connect to the network..
        /// </summary>
        public static string SDE_AUDIO_DOCUMENTS_NOT {
            get {
                return ResourceManager.GetString("SDE_AUDIO_DOCUMENTS_NOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Audio Documents page balance is 0.  Please purchase more pages to continue using the app..
        /// </summary>
        public static string SDE_AUDIO_DOCUMENTS_PAGE {
            get {
                return ResourceManager.GetString("SDE_AUDIO_DOCUMENTS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Audio Documents portal is unavailable.
        /// </summary>
        public static string SDE_AUDIO_DOCUMENTS_PORTAL {
            get {
                return ResourceManager.GetString("SDE_AUDIO_DOCUMENTS_PORTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Documents has been reset..
        /// </summary>
        public static string SDE_AUDIO_DOCUMENTS_RESET {
            get {
                return ResourceManager.GetString("SDE_AUDIO_DOCUMENTS_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Documents Service Unavailable.
        /// </summary>
        public static string SDE_AUDIO_DOCUMENTS_SERVICE {
            get {
                return ResourceManager.GetString("SDE_AUDIO_DOCUMENTS_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio File Expired.
        /// </summary>
        public static string SDE_AUDIO_FILE_EXPIRED {
            get {
                return ResourceManager.GetString("SDE_AUDIO_FILE_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Detect.
        /// </summary>
        public static string SDE_AUTO_DETECT {
            get {
                return ResourceManager.GetString("SDE_AUTO_DETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string SDE_BALANCE1 {
            get {
                return ResourceManager.GetString("SDE_BALANCE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bcc:.
        /// </summary>
        public static string SDE_BCC1 {
            get {
                return ResourceManager.GetString("SDE_BCC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best results achieved with simple document layouts without handwritten text, complex graphics or background color..
        /// </summary>
        public static string SDE_BEST_RESULTS_ACHIEVED {
            get {
                return ResourceManager.GetString("SDE_BEST_RESULTS_ACHIEVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black &amp; White.
        /// </summary>
        public static string SDE_BLACK_WHITE {
            get {
                return ResourceManager.GetString("SDE_BLACK_WHITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle Creation.
        /// </summary>
        public static string SDE_BUNDLE_CREATION {
            get {
                return ResourceManager.GetString("SDE_BUNDLE_CREATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle is invalid.
        /// </summary>
        public static string SDE_BUNDLE_INVALID {
            get {
                return ResourceManager.GetString("SDE_BUNDLE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By downloading and using this app, you acknowledge that you have read and understand our &lt;a href = “{0}“&gt;&lt;u&gt;Terms and Conditions&lt;/u&gt;&lt;/a&gt; and accept these terms of use and agree that you are legally bound by its terms. If you do not agree to these terms, please do not download and use the app and delete it from your mobile device..
        /// </summary>
        public static string SDE_BY_DOWNLOADING_USING {
            get {
                return ResourceManager.GetString("SDE_BY_DOWNLOADING_USING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SDE_CANCEL {
            get {
                return ResourceManager.GetString("SDE_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan.
        /// </summary>
        public static string SDE_CATALAN {
            get {
                return ResourceManager.GetString("SDE_CATALAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cc:.
        /// </summary>
        public static string SDE_CC1 {
            get {
                return ResourceManager.GetString("SDE_CC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These characters cannot be used: {0}.
        /// </summary>
        public static string SDE_CHARACTERS_CANNOT_BE {
            get {
                return ResourceManager.GetString("SDE_CHARACTERS_CANNOT_BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your device&apos;s network connection. If the problem Persists, contact your system administrator..
        /// </summary>
        public static string SDE_CHECK_DEVICES_NETWORK {
            get {
                return ResourceManager.GetString("SDE_CHECK_DEVICES_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Application.
        /// </summary>
        public static string SDE_CHOOSE_APPLICATION1 {
            get {
                return ResourceManager.GetString("SDE_CHOOSE_APPLICATION1", resourceCulture);
            }
        }
         
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SDE_CLOSE {
            get {
                return ResourceManager.GetString("SDE_CLOSE", resourceCulture);
            }
        }
        
 
        
  
      
        
      
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string SDE_CONNECTION_ERROR {
            get {
                return ResourceManager.GetString("SDE_CONNECTION_ERROR", resourceCulture);
            }
        }
     
        
        /// <summary>
        ///   Looks up a localized string similar to Contact your device administrator to enable these services..
        /// </summary>
        public static string SDE_CONTACT_DEVICE_ADMINISTRATOR {
            get {
                return ResourceManager.GetString("SDE_CONTACT_DEVICE_ADMINISTRATOR", resourceCulture);
            }
        }
 
 
  
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string SDE_CONTINUE {
            get {
                return ResourceManager.GetString("SDE_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Error.
        /// </summary>
        public static string SDE_CONVERSION_ERROR {
            get {
                return ResourceManager.GetString("SDE_CONVERSION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Failed.
        /// </summary>
        public static string SDE_CONVERSION_FAILED {
            get {
                return ResourceManager.GetString("SDE_CONVERSION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string SDE_CONVERT {
            get {
                return ResourceManager.GetString("SDE_CONVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert File.
        /// </summary>
        public static string SDE_CONVERT_FILE {
            get {
                return ResourceManager.GetString("SDE_CONVERT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting....
        /// </summary>
        public static string SDE_CONVERTING1 {
            get {
                return ResourceManager.GetString("SDE_CONVERTING1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2018. Xerox Corporation. All Rights Reserved..
        /// </summary>
        public static string SDE_COPYRIGHT_2018_XEROX {
            get {
                return ResourceManager.GetString("SDE_COPYRIGHT_2018_XEROX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2018  Xerox Corporation. All Rights Reserved..
        /// </summary>
        public static string SDE_COPYRIGHT_2018_XEROX1 {
            get {
                return ResourceManager.GetString("SDE_COPYRIGHT_2018_XEROX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {0} Xerox Corporation. All rights reserved..
        /// </summary>
        public static string SDE_COPYRIGHT_FMTSTR_XEROX {
            get {
                return ResourceManager.GetString("SDE_COPYRIGHT_FMTSTR_XEROX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the Audio Documents server..
        /// </summary>
        public static string SDE_COULD_NOT_CONNECT10 {
            get {
                return ResourceManager.GetString("SDE_COULD_NOT_CONNECT10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file at specified path..
        /// </summary>
        public static string SDE_COULD_NOT_FIND23 {
            get {
                return ResourceManager.GetString("SDE_COULD_NOT_FIND23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string SDE_COURSES {
            get {
                return ResourceManager.GetString("SDE_COURSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string SDE_CREATE_ACCOUNT2 {
            get {
                return ResourceManager.GetString("SDE_CREATE_ACCOUNT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Administrator Account.
        /// </summary>
        public static string SDE_CREATE_ADMINISTRATOR_ACCOUNT1 {
            get {
                return ResourceManager.GetString("SDE_CREATE_ADMINISTRATOR_ACCOUNT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create My Account.
        /// </summary>
        public static string SDE_CREATE_MY_ACCOUNT {
            get {
                return ResourceManager.GetString("SDE_CREATE_MY_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no sub-accounts.
        /// </summary>
        public static string SDE_CURRENTLY_HAVE_NO2 {
            get {
                return ResourceManager.GetString("SDE_CURRENTLY_HAVE_NO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string SDE_CZEK {
            get {
                return ResourceManager.GetString("SDE_CZEK", resourceCulture);
            }
        }
        
     
        
     
        
     
        
      
        
        /// <summary>
        ///   Looks up a localized string similar to Document Successfully Scanned..
        /// </summary>
        public static string SDE_DOCUMENT_SUCCESSFULLY_SCANNED {
            get {
                return ResourceManager.GetString("SDE_DOCUMENT_SUCCESSFULLY_SCANNED", resourceCulture);
            }
        }
        
      
        
      
     
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not a valid format..
        /// </summary>
        public static string SDE_EMAIL_NOT_VALID {
            get {
                return ResourceManager.GetString("SDE_EMAIL_NOT_VALID", resourceCulture);
            }
        }
        
     
        
        /// <summary>
        ///   Looks up a localized string similar to EMail.
        /// </summary>
        public static string SDE_EMAIL1 {
            get {
                return ResourceManager.GetString("SDE_EMAIL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SDE_EMAIL2 {
            get {
                return ResourceManager.GetString("SDE_EMAIL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string SDE_ENGLISH {
            get {
                return ResourceManager.GetString("SDE_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a different email address.
        /// </summary>
        public static string SDE_ENTER_DIFFERENT_EMAIL {
            get {
                return ResourceManager.GetString("SDE_ENTER_DIFFERENT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        public static string SDE_ENTER_EMAIL {
            get {
                return ResourceManager.GetString("SDE_ENTER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an email address.
        /// </summary>
        public static string SDE_ENTER_EMAIL_ADDRESS20 {
            get {
                return ResourceManager.GetString("SDE_ENTER_EMAIL_ADDRESS20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email Address.
        /// </summary>
        public static string SDE_ENTER_EMAIL_ADDRESS9 {
            get {
                return ResourceManager.GetString("SDE_ENTER_EMAIL_ADDRESS9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email to receive link to audio.
        /// </summary>
        public static string SDE_ENTER_EMAIL_RECEIVE {
            get {
                return ResourceManager.GetString("SDE_ENTER_EMAIL_RECEIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter File Name.
        /// </summary>
        public static string SDE_ENTER_FILE_NAME1 {
            get {
                return ResourceManager.GetString("SDE_ENTER_FILE_NAME1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string SDE_ENTER_PASSWORD_2 {
            get {
                return ResourceManager.GetString("SDE_ENTER_PASSWORD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password.
        /// </summary>
        public static string SDE_ENTER_PASSWORD3 {
            get {
                return ResourceManager.GetString("SDE_ENTER_PASSWORD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Server Address.
        /// </summary>
        public static string SDE_ENTER_SERVER_ADDRESS {
            get {
                return ResourceManager.GetString("SDE_ENTER_SERVER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid TCP port and DNS name..
        /// </summary>
        public static string SDE_ENTER_TCP_PORT1 {
            get {
                return ResourceManager.GetString("SDE_ENTER_TCP_PORT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least {0} characters.
        /// </summary>
        public static string SDE_ENTERT_LEAST_FMTSTR {
            get {
                return ResourceManager.GetString("SDE_ENTERT_LEAST_FMTSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least %@ characters.
        /// </summary>
        public static string SDE_ENTERT_LEAST_PCTCHARACTERS {
            get {
                return ResourceManager.GetString("SDE_ENTERT_LEAST_PCTCHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string SDE_ERROR {
            get {
                return ResourceManager.GetString("SDE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string SDE_ERROR_OCCURRED {
            get {
                return ResourceManager.GetString("SDE_ERROR_OCCURRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your file..
        /// </summary>
        public static string SDE_ERROR_PROCESSING_FILE {
            get {
                return ResourceManager.GetString("SDE_ERROR_PROCESSING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error working with server, try again later..
        /// </summary>
        public static string SDE_ERROR_WORKING_SERVER {
            get {
                return ResourceManager.GetString("SDE_ERROR_WORKING_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string SDE_EXIT {
            get {
                return ResourceManager.GetString("SDE_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string SDE_EXPIRED {
            get {
                return ResourceManager.GetString("SDE_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires:.
        /// </summary>
        public static string SDE_EXPIRES {
            get {
                return ResourceManager.GetString("SDE_EXPIRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires in: 1 day.
        /// </summary>
        public static string SDE_EXPIRES_IN_1 {
            get {
                return ResourceManager.GetString("SDE_EXPIRES_IN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires in: &lt; 1 day.
        /// </summary>
        public static string SDE_EXPIRES_IN_11 {
            get {
                return ResourceManager.GetString("SDE_EXPIRES_IN_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires in: {0} days.
        /// </summary>
        public static string SDE_EXPIRES_IN_FMTSTR {
            get {
                return ResourceManager.GetString("SDE_EXPIRES_IN_FMTSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string SDE_FEMALE {
            get {
                return ResourceManager.GetString("SDE_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string SDE_FILE {
            get {
                return ResourceManager.GetString("SDE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Access Error.
        /// </summary>
        public static string SDE_FILE_ACCESS_ERROR1 {
            get {
                return ResourceManager.GetString("SDE_FILE_ACCESS_ERROR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Format.
        /// </summary>
        public static string SDE_FILE_FORMAT {
            get {
                return ResourceManager.GetString("SDE_FILE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string SDE_FILE_NAME {
            get {
                return ResourceManager.GetString("SDE_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        public static string SDE_FILE_NOT_FOUND6 {
            get {
                return ResourceManager.GetString("SDE_FILE_NOT_FOUND6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File settings.
        /// </summary>
        public static string SDE_FILE_SETTINGS {
            get {
                return ResourceManager.GetString("SDE_FILE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string SDE_FILES {
            get {
                return ResourceManager.GetString("SDE_FILES", resourceCulture);
            }
        }
        
       
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [Date &amp; Time].{1}.
        /// </summary>
        public static string SDE_FMTSTR_DATE_TIMEFMTSTR {
            get {
                return ResourceManager.GetString("SDE_FMTSTR_DATE_TIMEFMTSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} {2} has invited you to create a Xerox® Audio Documents account. Please click the button below to create your account. If you have any questions about this invitation, please reply to {3}..
        /// </summary>
        public static string SDE_FMTSTR_FMTSTR_INVITED {
            get {
                return ResourceManager.GetString("SDE_FMTSTR_FMTSTR_INVITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Pages.
        /// </summary>
        public static string SDE_FMTSTR_PAGES {
            get {
                return ResourceManager.GetString("SDE_FMTSTR_PAGES", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to ©{0} Xerox Corporation. All rights reserved. XEROX® and Xerox and Design® are trademarks of Xerox Corporation in the United States and/or other countries..
        /// </summary>
        public static string SDE_FMTSTR_XEROX_CORPORATION {
            get {
                return ResourceManager.GetString("SDE_FMTSTR_XEROX_CORPORATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © {0}-{1} Xerox Corporation. All Rights Reserved..
        /// </summary>
        public static string SDE_FMTSTRFMTSTR_XEROX_CORPORATION {
            get {
                return ResourceManager.GetString("SDE_FMTSTRFMTSTR_XEROX_CORPORATION", resourceCulture);
            }
        }
        
        
        
       
        
 
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale.
        /// </summary>
        public static string SDE_GRAYSCALE {
            get {
                return ResourceManager.GetString("SDE_GRAYSCALE", resourceCulture);
            }
        }
        
 
        
 
 
        
        /// <summary>
        ///   Looks up a localized string similar to If the error persists, exit and try again later..
        /// </summary>
        public static string SDE_IF_ERROR_PERSISTS1 {
            get {
                return ResourceManager.GetString("SDE_IF_ERROR_PERSISTS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the problem persists, contact Xerox support..
        /// </summary>
        public static string SDE_IF_PROBLEM_PERSISTS3 {
            get {
                return ResourceManager.GetString("SDE_IF_PROBLEM_PERSISTS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the problem persists, please contact Xerox support..
        /// </summary>
        public static string SDE_IF_PROBLEM_PERSISTS4 {
            get {
                return ResourceManager.GetString("SDE_IF_PROBLEM_PERSISTS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Only.
        /// </summary>
        public static string SDE_IMAGE_ONLY {
            get {
                return ResourceManager.GetString("SDE_IMAGE_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial release.
        /// </summary>
        public static string SDE_INITIAL_RELEASE {
            get {
                return ResourceManager.GetString("SDE_INITIAL_RELEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Scan Size Not Determined.
        /// </summary>
        public static string SDE_INPUT_SCAN_SIZE {
            get {
                return ResourceManager.GetString("SDE_INPUT_SCAN_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input scan size not determined..
        /// </summary>
        public static string SDE_INPUT_SCAN_SIZE1 {
            get {
                return ResourceManager.GetString("SDE_INPUT_SCAN_SIZE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of ConnectKey Apps (Weblets) is disabled at the device..
        /// </summary>
        public static string SDE_INSTALLATION_CONNECTKEY_APPS {
            get {
                return ResourceManager.GetString("SDE_INSTALLATION_CONNECTKEY_APPS", resourceCulture);
            }
        }
        
     
     
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue converting:.
        /// </summary>
        public static string SDE_ISSUE_CONVERTING {
            get {
                return ResourceManager.GetString("SDE_ISSUE_CONVERTING", resourceCulture);
            }
        }
        
     
        
     
        
        /// <summary>
        ///   Looks up a localized string similar to The job has been canceled..
        /// </summary>
        public static string SDE_JOB_CANCELED1 {
            get {
                return ResourceManager.GetString("SDE_JOB_CANCELED1", resourceCulture);
            }
        }
        
      
        
        /// <summary>
        ///   Looks up a localized string similar to The job has timed out.
        /// </summary>
        public static string SDE_JOB_TIMED_OUT {
            get {
                return ResourceManager.GetString("SDE_JOB_TIMED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jpg is unavailable while Black &amp; White is selected..
        /// </summary>
        public static string SDE_JPG_UNAVAILABLE_WHILE {
            get {
                return ResourceManager.GetString("SDE_JPG_UNAVAILABLE_WHILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jpg is unavailable while Output Color Auto Detect is selected..
        /// </summary>
        public static string SDE_JPG_UNAVAILABLE_WHILE1 {
            get {
                return ResourceManager.GetString("SDE_JPG_UNAVAILABLE_WHILE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SDE_LANGUAGE {
            get {
                return ResourceManager.GetString("SDE_LANGUAGE", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Error.
        /// </summary>
        public static string SDE_LAUNCH_ERROR {
            get {
                return ResourceManager.GetString("SDE_LAUNCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License agreement.
        /// </summary>
        public static string SDE_LICENSE_AGREEMENT {
            get {
                return ResourceManager.GetString("SDE_LICENSE_AGREEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Agreement.
        /// </summary>
        public static string SDE_LICENSE_AGREEMENT1 {
            get {
                return ResourceManager.GetString("SDE_LICENSE_AGREEMENT1", resourceCulture);
            }
        }
        
       
        
        
        
        
        
        
        
       
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string SDE_LOADING {
            get {
                return ResourceManager.GetString("SDE_LOADING", resourceCulture);
            }
        }
        
      
      
        
      
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum pages per job.
        /// </summary>
        public static string SDE_MAXIMUM_PAGES_PER {
            get {
                return ResourceManager.GetString("SDE_MAXIMUM_PAGES_PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string SDE_MORE {
            get {
                return ResourceManager.GetString("SDE_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SDE_NAME {
            get {
                return ResourceManager.GetString("SDE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        public static string SDE_NETWORK_ERROR {
            get {
                return ResourceManager.GetString("SDE_NETWORK_ERROR", resourceCulture);
            }
        }
        
       
        
      
        
     
        
      
        /// <summary>
        ///   Looks up a localized string similar to No Text to Convert.
        /// </summary>
        public static string SDE_NO_TEXT_CONVERT {
            get {
                return ResourceManager.GetString("SDE_NO_TEXT_CONVERT", resourceCulture);
            }
        }
        
      
        
     
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string SDE_OK {
            get {
                return ResourceManager.GetString("SDE_OK", resourceCulture);
            }
        }
        
      
        
        /// <summary>
        ///   Looks up a localized string similar to Original not detected..
        /// </summary>
        public static string SDE_ORIGINAL_NOT_DETECTED {
            get {
                return ResourceManager.GetString("SDE_ORIGINAL_NOT_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Size.
        /// </summary>
        public static string SDE_ORIGINAL_SIZE {
            get {
                return ResourceManager.GetString("SDE_ORIGINAL_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string SDE_OTHER1 {
            get {
                return ResourceManager.GetString("SDE_OTHER1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Color.
        /// </summary>
        public static string SDE_OUTPUT_COLOR2 {
            get {
                return ResourceManager.GetString("SDE_OUTPUT_COLOR2", resourceCulture);
            }
        }
        
     
        
        /// <summary>
        ///   Looks up a localized string similar to Place your original in the feeder or on the glass, and try again..
        /// </summary>
        public static string SDE_PLACE_ORIGINAL_FEEDER {
            get {
                return ResourceManager.GetString("SDE_PLACE_ORIGINAL_FEEDER", resourceCulture);
            }
        }
        
       
        /// <summary>
        ///   Looks up a localized string similar to Please agree to continue.
        /// </summary>
        public static string SDE_PLEASE_AGREE_CONTINUE {
            get {
                return ResourceManager.GetString("SDE_PLEASE_AGREE_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your document and rescan to try again..
        /// </summary>
        public static string SDE_PLEASE_CHECK_DOCUMENT {
            get {
                return ResourceManager.GetString("SDE_PLEASE_CHECK_DOCUMENT", resourceCulture);
            }
        }
        
      
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your network connections and try again..
        /// </summary>
        public static string SDE_PLEASE_CHECK_NETWORK {
            get {
                return ResourceManager.GetString("SDE_PLEASE_CHECK_NETWORK", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address.
        /// </summary>
        public static string SDE_PLEASE_ENTER_EMAIL9 {
            get {
                return ResourceManager.GetString("SDE_PLEASE_ENTER_EMAIL9", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the required field: Email.
        /// </summary>
        public static string SDE_PLEASE_FILL_REQUIRED2 {
            get {
                return ResourceManager.GetString("SDE_PLEASE_FILL_REQUIRED2", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the required fields.
        /// </summary>
        public static string SDE_PLEASE_FILL_REQUIRED5 {
            get {
                return ResourceManager.GetString("SDE_PLEASE_FILL_REQUIRED5", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Please rescan your document to try again..
        /// </summary>
        public static string SDE_PLEASE_RESCAN_DOCUMENT {
            get {
                return ResourceManager.GetString("SDE_PLEASE_RESCAN_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the device and try again. If the Problem persists, contact Xerox support.
        /// </summary>
        public static string SDE_PLEASE_RESTART_DEVICE {
            get {
                return ResourceManager.GetString("SDE_PLEASE_RESTART_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again..
        /// </summary>
        public static string SDE_PLEASE_TRY_AGAIN1 {
            get {
                return ResourceManager.GetString("SDE_PLEASE_TRY_AGAIN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later..
        /// </summary>
        public static string SDE_PLEASE_TRY_AGAIN2 {
            get {
                return ResourceManager.GetString("SDE_PLEASE_TRY_AGAIN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later. If the problem persists, contact Xerox support..
        /// </summary>
        public static string SDE_PLEASE_TRY_AGAIN6 {
            get {
                return ResourceManager.GetString("SDE_PLEASE_TRY_AGAIN6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again in 24 hours..
        /// </summary>
        public static string SDE_PLEASE_TRY_AGAIN8 {
            get {
                return ResourceManager.GetString("SDE_PLEASE_TRY_AGAIN8", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until job completes before scanning again..
        /// </summary>
        public static string SDE_PLEASE_WAIT_UNTIL {
            get {
                return ResourceManager.GetString("SDE_PLEASE_WAIT_UNTIL", resourceCulture);
            }
        }
        
        
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to Scan.
        /// </summary>
        public static string SDE_PREPARING_SCAN {
            get {
                return ResourceManager.GetString("SDE_PREPARING_SCAN", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string SDE_PRIVACY {
            get {
                return ResourceManager.GetString("SDE_PRIVACY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string SDE_PRIVACY_POLICY {
            get {
                return ResourceManager.GetString("SDE_PRIVACY_POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SDE_PRIVACY_STATEMENT {
            get {
                return ResourceManager.GetString("SDE_PRIVACY_STATEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem converting your file..
        /// </summary>
        public static string SDE_PROBLEM_CONVERTING_FILE {
            get {
                return ResourceManager.GetString("SDE_PROBLEM_CONVERTING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with your login. Try again later or contact customer service. Code: {0}.
        /// </summary>
        public static string SDE_PROBLEM_LOGIN_TRY {
            get {
                return ResourceManager.GetString("SDE_PROBLEM_LOGIN_TRY", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem. Try again later or contact customer service. Code: {0}.
        /// </summary>
        public static string SDE_PROBLEM_TRY_AGAIN {
            get {
                return ResourceManager.GetString("SDE_PROBLEM_TRY_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string SDE_PROCESSING {
            get {
                return ResourceManager.GetString("SDE_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Error.
        /// </summary>
        public static string SDE_PROCESSING_ERROR {
            get {
                return ResourceManager.GetString("SDE_PROCESSING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string SDE_PROFILE1 {
            get {
                return ResourceManager.GetString("SDE_PROFILE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase additional pages to continue..
        /// </summary>
        public static string SDE_PURCHASE_ADDITIONAL_PAGES {
            get {
                return ResourceManager.GetString("SDE_PURCHASE_ADDITIONAL_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA, Version.
        /// </summary>
        public static string SDE_QA_VERSION {
            get {
                return ResourceManager.GetString("SDE_QA_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string SDE_QUANTITY {
            get {
                return ResourceManager.GetString("SDE_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity cannot be more than 9999..
        /// </summary>
        public static string SDE_QUANTITY_CANNOT_BE {
            get {
                return ResourceManager.GetString("SDE_QUANTITY_CANNOT_BE", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string SDE_REGISTRATION {
            get {
                return ResourceManager.GetString("SDE_REGISTRATION", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to This is a required field..
        /// </summary>
        public static string SDE_REQUIRED_FIELD1 {
            get {
                return ResourceManager.GetString("SDE_REQUIRED_FIELD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string SDE_RESET {
            get {
                return ResourceManager.GetString("SDE_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string SDE_RETRY {
            get {
                return ResourceManager.GetString("SDE_RETRY", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SDE_SAVE {
            get {
                return ResourceManager.GetString("SDE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string SDE_SAVED {
            get {
                return ResourceManager.GetString("SDE_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string SDE_SCAN {
            get {
                return ResourceManager.GetString("SDE_SCAN", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Extension &lt;/br&gt; Scan Template Management &lt;/br&gt; Job Management Extension&lt;div style=&apos;padding-top:10px;&apos;&gt;Contact your device administrator to enable these services.&lt;/div&gt;.
        /// </summary>
        public static string SDE_SCAN_EXTENSION_SCAN1 {
            get {
                return ResourceManager.GetString("SDE_SCAN_EXTENSION_SCAN1", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SDE_SELECT_ALL {
            get {
                return ResourceManager.GetString("SDE_SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a service problem. Try again later or contact customer service. Code: {0}.
        /// </summary>
        public static string SDE_SERVICE_PROBLEM_TRY {
            get {
                return ResourceManager.GetString("SDE_SERVICE_PROBLEM_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service you are trying to use may be temporarily unavailable..
        /// </summary>
        public static string SDE_SERVICE_TRYING_USE {
            get {
                return ResourceManager.GetString("SDE_SERVICE_TRYING_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SDE_SOMETHING_WENT_WRONG {
            get {
                return ResourceManager.GetString("SDE_SOMETHING_WENT_WRONG", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SDE_STATUS {
            get {
                return ResourceManager.GetString("SDE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        public static string SDE_SUBJECT3 {
            get {
                return ResourceManager.GetString("SDE_SUBJECT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string SDE_SUPPORT {
            get {
                return ResourceManager.GetString("SDE_SUPPORT", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string SDE_TERMS_CONDITIONS {
            get {
                return ResourceManager.GetString("SDE_TERMS_CONDITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string SDE_TERMS_SERVICE1 {
            get {
                return ResourceManager.GetString("SDE_TERMS_SERVICE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string SDE_TERMS1 {
            get {
                return ResourceManager.GetString("SDE_TERMS1", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        public static string SDE_THANK_YOU {
            get {
                return ResourceManager.GetString("SDE_THANK_YOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tif is unavailable while Output Color Auto Detect is selected..
        /// </summary>
        public static string SDE_TIF_UNAVAILABLE_WHILE {
            get {
                return ResourceManager.GetString("SDE_TIF_UNAVAILABLE_WHILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string SDE_TITLE {
            get {
                return ResourceManager.GetString("SDE_TITLE", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to To use this app, the following web service(s) must be enabled..
        /// </summary>
        public static string SDE_TO_USE_APP {
            get {
                return ResourceManager.GetString("SDE_TO_USE_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string SDE_TO5 {
            get {
                return ResourceManager.GetString("SDE_TO5", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string SDE_TRY_AGAIN {
            get {
                return ResourceManager.GetString("SDE_TRY_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try lowering the resolution or scan your document as multiple jobs..
        /// </summary>
        public static string SDE_TRY_LOWERING_RESOLUTION {
            get {
                return ResourceManager.GetString("SDE_TRY_LOWERING_RESOLUTION", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string SDE_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("SDE_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an unmonitored E-mail address. Please do not reply to this E-mail. Select the Support link below for assistance.
        /// </summary>
        public static string SDE_UNMONITORED_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("SDE_UNMONITORED_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string SDE_UPLOADING2 {
            get {
                return ResourceManager.GetString("SDE_UPLOADING2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string SDE_VERSION {
            get {
                return ResourceManager.GetString("SDE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string SDE_VERSION_FMTSTR {
            get {
                return ResourceManager.GetString("SDE_VERSION_FMTSTR", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Xerox Scan.
        /// </summary>
        public static string SDE_XEROX_SCAN {
            get {
                return ResourceManager.GetString("SDE_XEROX_SCAN", resourceCulture);
            }
        }
    }
}
